### ISSUE TITLE
Still exists if switching with Alt-Tab

### ISSUE THREAD

**Issue by bennylp** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#11]
First of all, thanks for making this fix! I'm still having a problem though.

I'm on:
- Ubuntu 22.04.1 LTS
- Gnome 42.5
- VSCode 1.74.2
- This extension downloaded from GitHub

Steps to reproduce:
1. Open editor in VSCode, scroll to a position around mid point of the file
2. Switch to Firefox. Scroll with mouse wheel
3. Switch back to VSCode. Scroll a little.

In step 3, if I switch with Alt-Tab, the editor position in step 3 will jump erratically. However if I switch with mouse click, the problem seems to be solved.

Note that Alt-Tab is already set to Switch Windows in GNOME Keyboard Shortcuts. I've also logout/re-login to make sure things are started.

Is this the same problem as #2?

Let me know if you need any more info. Thanks.

**Comment by lucasresck** [comment]
Hi, @bennylp, thanks for opening this issue!

I tried to reproduce the problem (same software versions with extension downloaded from GNOME Extensions) but I only could reproduce it when the extension was deactivated.

What you described is what the extension was designed and tested to solve. Although it was first developed to  `Alt + Tab` being set to `switch-windows`, it works with `switch-applications` now too (https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/2).

What do you mean by "switching with mouse click"? Does it mean pressing the `Super` key and clicking over the desired window? There's an open issue (https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/10) describing this problem and the fact that the extension doesn't solve it. Can you confirm that this problem exists and it is this extension that solves it?

**Comment by bennylp** [comment]
> Hi, @bennylp, thanks for opening this issue!

Thanks for responding!

> I tried to reproduce the problem (same software versions with extension downloaded from GNOME Extensions) but I only could reproduce it when the extension was deactivated.

Right, I think I know what's wrong:

```
$ gnome-extensions show alt-tab-scroll-workaround@lucasresck.github.io
alt-tab-scroll-workaround@lucasresck.github.io
  Name: Alt+Tab Scroll Workaround
  Description: Temporary fix for a bug that buffers the scroll between different windows (e.g., Chrome and VS Code).
  Path: /home/bennylp/.local/share/gnome-shell/extensions/alt-tab-scroll-workaround@lucasresck.github.io
  URL: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround
  Version: 3
  State: INITIALIZED
```
It's in `INITIALIZED` state, even after I run `gnome-extensions enable alt-tab-scroll-workaround@lucasresck.github.io` to it (also tried `make enable`, which I believe is the same thing). I have tried to logout/relogin for good measure as well, same result.

> What do you mean by "switching with mouse click"? Does it mean pressing the `Super` key and clicking over the desired window? 

By clicking, I mean just to click any visible VScode window to bring it to focus. Not with super key.

> There's an open issue (#10) describing this problem and the fact that the extension doesn't solve it. Can you confirm that this problem exists and it is this extension that solves it?

The problem exists here too and it's not solved by this extension.

Please let me know if there's anything I should try. Thanks.

**Comment by lucasresck** [comment]
> It's in `INITIALIZED` state, even after I run `gnome-extensions enable alt-tab-scroll-workaround@lucasresck.github.io` to it (also tried `make enable`, which I believe is the same thing). I have tried to logout/relogin for good measure as well, same result.

Hi, this is probably the problem. In my machine it says `State: ENABLED`. I believe logging out and logging in should solve it, but you may also try pressing `Alt + F2` and typing `r` to restart GNOME Shell.

You can manage the installed and enabled extensions through the Extensions app that comes with GNOME or through https://extensions.gnome.org/local/. The extension should be "ON" in both of them. You may also try installing the extension from the GNOME Extensions website itself: [Alt+Tab Scroll Workaround](https://extensions.gnome.org/extension/5282/alttab-scroll-workaround/).



> By clicking, I mean just to click any visible VScode window to bring it to focus. Not with super key.
> 
> >

Oh, I see, so this is a different situation. And it seems there's not a problem in this situation, which is good 🙂

**Comment by bennylp** [comment]
Right, I think I found the reason. I install and run `gnome-extensions-app`:

```
$ sudo apt-get install gnome-shell-extension-prefs
$ gnome-extensions-app
```
And as it turns out, **Extensions** is disabled (see screenshot below). I think this means 3rd party extensions are disabled? (because the built-in extensions are running). I don't recall disabling this, so it could be some app or upgrade disabled it?

![Screenshot from 2022-12-29 08-15-06](https://user-images.githubusercontent.com/4054644/209891311-1a908c44-8c12-42fe-8f6e-1c3208b22132.png)

Setting **Extensions** to ON automatically sets the Alt-Tab extension to ON, and things work as expected!

So I think what works/doesn't work are as expected:
- Alt-Tab (switch windows) works
- Super-Tab (switch application) works
- I can confirm #10 is also happening

Thanks again for the work, you may close this ticket.

**Comment by bennylp** [comment]
> You can manage the installed and enabled extensions through the Extensions app that comes with GNOME 

Reading this again, now I understood what you meant. The Extensions app (GUI) was not installed in my system, so I thought you meant `gnome-extensions` CLI app.

**Comment by lucasresck** [comment]
> Setting **Extensions** to ON automatically sets the Alt-Tab extension to ON, and things work as expected!

Good! Thanks for investigating this, happy this is working now.

I'm not sure but I think Extensions GUI app comes pre-installed on Ubuntu. I'm also not sure if the GUI app is required for everything to work. But at least it's working now.

Feel free to reopen this issue or opening another one!
