### ISSUE TITLE
broken?

### ISSUE THREAD

**Issue by knoopx** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#12]
looks like it broke with gnome 43.3, having random scroll jumps again

**Comment by lucasresck** [comment]
Hi, thanks for the issue.

Which is your operating system? In which version?

Was the extension working before the update? Have you tried reinstalling the extension?

Sometimes the GNOME extensions deactivate automatically. Are your extensions active?

**Comment by knoopx** [comment]
i'm on arch linux, extension is activate and it worked previously before upgrading to 43.3 (which was somewhere between this and the past week)

**Comment by lucasresck** [comment]
Which Arch Linux is yours?

And thanks for the feedback. Possible ways to advance this are testing this behavior in other systems with GNOME 43.3 and studying the code of this new version to check if the extension still follows the GNOME implementation.

I currently don't have access to this GNOME version and not much free time to study the code; I'll wait for more reports of this bug before tackling it.

If I may, I also invite you into this. As a suggestion, I would recommend taking a look at the way the two inherited classes in [extension.js](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/fede46dd2fb6fbd2368ca441754da87130c7e55e/extension.js) relate to the [js/ui/altTab.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/022c64961c22afcfe865186b5e190a7c9446ff15/js/ui/altTab.js) file of gnome-shell. A possible advance would be checking if this is maintained in the new version. Another direction is checking the log of `gnome-shell`, including adding `console.log` into `extension.js` to check the extension behavior.

Thanks again!

**Comment by knoopx** [comment]
hey @lucasresck thanks, will definitely check but I will wait until 44 is out given is around the corner

**Comment by lucasresck** [comment]
Hi, @knoopx! Any update about the functioning of the extension? Have you upgraded GNOME to 44?

**Comment by knoopx** [comment]
@lucasresck something fixed it along the way, been running 44 for a while without issues

**Comment by lucasresck** [comment]
Thanks, @knoopx! Let me know any issue.
