### ISSUE TITLE
[Question] Does it work/run in GNOME 44?

### ISSUE THREAD

**Issue by lochetti** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#13]
I have recently updated to Fedora 38 which comes with GNOME 44 and when I open https://extensions.gnome.org/extension/5282/alttab-scroll-workaround/ it says INCOMPATIBLE

![image](https://user-images.githubusercontent.com/2541422/233324411-8e957f4c-8067-419c-8736-269c6b628232.png)

I am assuming that this is because I am using GNOME 44. Is that it?

Thanks! :)

**Comment by lucasresck** [comment]
Hi, this is it! Thanks for the feedback.

I couldn't test if the extension works well on GNOME 44 yet, so I didn't add this version to the list of supported GNOME versions.

Even though GNOME Extensions website says the extension is incompatible, you are able to install it using this repository and manual commands: [Installation from GitHub](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#installation-from-github).

If you successfully install the extension in GNOME 44, please, let me know so I can gather information to eventually upgrade the extension to this new GNOME version.

Feel free to reopen this issue if you have new information or more questions. Thank you again!

**Comment by lucasresck** [comment]
Hi, the extension is already updated to support GNOME 44. Thank you!
