### ISSUE TITLE
Only affects X11; disable on Wayland?

### ISSUE THREAD

**Issue by Arcitec** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#15]
Hi Lucas, thank you so much for creating this extension. I am still an X11 user thanks to having NVIDIA hardware.

I just thought that it would be good to mention in the Readme that this project isn't required on Wayland. I see from the list of links in the Readme that everybody is saying that the issue only happens on Mutter (GNOME) on X11. No other window managers have the issue. And Mutter works perfectly on Wayland.

There is a section in the Readme here that even gives people instructions about how to install the extension on Wayland, which seems backwards if it's true that Wayland doesn't have the issue. 😉

Maybe even put in a code block that makes the extension do nothing (no hooks at all) if it detects Wayland. Here is an example of an extension that detects Wayland. Same trick could be used here:

https://github.com/injcristianrojas/waylandorx11

I anticipate being stuck for about 1-2 more years on X11, at least. [NVIDIA loses 10-15% FPS when gaming on Wayland](https://www.phoronix.com/review/wayland-nv-amd-2023) (which could take years for them to fix), and has a ton of other issues, so I thank you again for creating this workaround. Awesome work.

---

# Edit in 2025: Yes it only affects X11. It's fixed on Wayland. More details here:

https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/43#issuecomment-3065560240

**Comment by Arcitec** [comment]
Regarding the suggestion to make the extension "do nothing" if the user is on Wayland, this seems to be the code to detect Wayland:

```js
const { Meta } = imports.gi;
Meta.is_wayland_compositor()
```

**Comment by lucasresck** [comment]
Hi, @Arcitec, thank you for reaching out. And sorry for my delay.

I believe it's true (but I didn't check it systematically) that the scroll issue doesn't appear on Wayland. I remember trying Wayland when I first discovered this issue (as a suggested workaround) but I had screen sharing problems at that time, so I came back to X11.

Considering that one only reaches out to the extension when they have this problem, is it really necessary to specify the prerequisites for the issue itself? I mean, if a GNOME user arrives to the extension page, they would have the issue, therefore they wouldn't be using Wayland. It seems not to be necessary to spend efforts in predicting situations that are at first impossible to happen (an Wayland user trying to install the extension). What do you think?

And about the `README`, it currently doesn't give instructions for Wayland. It was the case an user sent a [pull request](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/1) that, among other things, would add Wayland instructions, but after [my comment](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/1#issuecomment-1190979161) they [removed it](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/1/commits/e451be8f2082648c1590aa04e798a51d057c940f).

Thank you again!
