### ISSUE TITLE
Seems to have stopped working recently in PopOS.

### ISSUE THREAD

**Issue by mattemoore** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#16]
![image](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/assets/8275624/e13a6d8e-c5b2-4adb-9519-603adf3b504b)
Installation confirmed as per screenshot but the odd scrolling behaviour is back.

System information in screenshot below.  If you need me to debug or anything let me know.

![image](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/assets/8275624/55221ec7-351a-4c6d-bf1b-5b296a451a7d)

**Comment by lucasresck** [comment]
Hi, @mattemoore, thank you for your feedback!

As you said, you have the scroll problem back (so it was working before) even though the extension is active. This should not be the case as GNOME 42 is supported and it was tested. This also works on my machine (Ubuntu 22.04, GNOME 42.5).

At first, I would suggest you to reinstall the extension by clicking "Remove" and installing from the GNOME Extensions website again. If it doesn't solve it, try to [manually install the extension from the GitHub repository](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#installation-from-github).

If this still doesn't solve it, we may have to debug why this is not working. Try running
```
journalctl /usr/bin/gnome-shell
```
to check for any errors while using the extension. Also, as a quick start, take a look at [these docs](https://gjs.guide/extensions/development/debugging.html#logging) to log the extension.

Please, let me know if the problem still persists and what were your findings regarding this!

**Comment by farfromrefug** [comment]
@lucasresck just to confirm i also have the issue again in popos. Was working before

**Comment by lucasresck** [comment]
> @lucasresck just to confirm i also have the issue again in popos. Was working before

Thanks, @farfromrefug. Could you please follow the steps from @mattemoore's comment and my last comment to help debugging this problem?

**Comment by mattemoore** [comment]
No errors with extension.  No errors around timestamps when I alt-tab between vsCode and Chrome.

un 13 19:23:17 pop-os gnome-shell[3036]: [VERTICAL_OVERVIEW] enabled
Jun 13 19:23:17 pop-os gnome-shell[3036]: gnome-shell-extension-system76-power: power profile was set: 'Balanced'
Jun 13 19:23:18 pop-os gnome-shell[3036]: [popx11gestures@system76.com] Connection with Touchégg established
Jun 13 19:23:18 pop-os gnome-shell[3036]: Error looking up permission: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for geolocation
Jun 13 19:23:19 pop-os gnome-shell[3036]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jun 13 19:23:20 pop-os gnome-shell[3036]: Ignoring length property that isn't a number at line 4, col 20
Jun 13 19:23:20 pop-os gnome-shell[3036]: GNOME Shell started at Tue Jun 13 2023 19:23:17 GMT-0400 (EDT)
Jun 13 19:23:20 pop-os gnome-shell[3036]: Registering session with GDM
Jun 13 19:23:20 pop-os ubuntu-appindicators@ubuntu.com[3036]: Impossible to send about-to-show to menu: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.E>
Jun 13 19:23:21 pop-os gnome-shell[3036]: DING: Detected async api for thumbnails
Jun 13 19:23:21 pop-os gnome-shell[3036]: DING: GNOME nautilus 42.6
Jun 13 19:23:42 pop-os gnome-shell[3036]: Ignoring length property that isn't a number at line 4, col 20
Jun 13 19:24:40 pop-os gnome-shell[3036]: Window manager warning: Overwriting existing binding of keysym ff61 with keysym ff61 (keycode 6b).
Jun 13 19:27:15 pop-os ubuntu-appindicators@ubuntu.com[3036]: unable to update icon for unityhub1
Jun 13 19:27:15 pop-os ubuntu-appindicators@ubuntu.com[3036]: unable to update icon for unityhub1
Jun 13 19:27:25 pop-os gnome-shell[3036]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6800129
Jun 13 19:27:25 pop-os gnome-shell[3036]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6800144
Jun 13 19:27:26 pop-os gnome-shell[3036]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x6c00129
Jun 13 19:27:35 pop-os gnome-shell[3036]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x680028f
Jun 13 19:27:35 pop-os gnome-shell[3036]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x68002a8
Jun 13 19:30:27 pop-os ubuntu-appindicators@ubuntu.com[3036]: unable to update icon for blueman

 ~                                                                                                                               INT х  15s  ≡  19:34:37

**Comment by lucasresck** [comment]
Hi again!

Another user of Pop!_OS recently reported they can use the extension (https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/18), even though they experience another problem.

**Comment by lucasresck** [comment]
Hi, @mattemoore, does this problem still happen?

**Comment by lucasresck** [comment]
I'll close this issue, feel free to reopen it or create another issue if necessary.
