### ISSUE TITLE
frequently after apt upgrades must disable/enable

### ISSUE THREAD

**Issue by LionelHolt** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#18]
Frequently after apt upgrades, this workaround stops working until I disable it then enable again. That has worked for me every time, but is a bit annoying. Is this a known issue and is there a solution to avoid having to disable/enable? My system is Pop!_OS 22.04 LTS.

**Comment by lucasresck** [comment]
Hi! Thanks for reaching out.

I am aware that some GNOME Extensions do disable randomly (not sure whether it is related to `apt` updates and generally I just need to enable them again, without disabling them first).

But it happens with other extensions as well. I don't think there is something special with this extension in comparison to other extensions.

Do you observed this same behavior with other GNOME Extensions?

Thank you :)

**Comment by LionelHolt** [comment]
The extension isn't disabled. It just doesn't work anymore after certain apt upgrades. I have to manually disabled then re-enable. This does not happen with any other extensions, at least not that I'm aware. I'll pay more attention to future upgrades and hopefully catch the pattern of which specific upgrades cause this extension to stop working. It might be kernel upgrades?

**Comment by lucasresck** [comment]
Interesting. I'll keep an eye on the functioning of the extension after upgrades.

Please, get in touch if there's more information!

Thank you again for reaching out :)

**Comment by lucasresck** [comment]
Hi, @LionelHolt, does this issue keep happening? Especially after upgrading to GNOME 45, if this is your case?

**Comment by LionelHolt** [comment]
It does keep happening  and I haven't identified a pattern. I'm on Gnome 42 due to sticking with Pop!_OS 22.04 LTS. I'm in the middle of migrating 15 website so not able to experiment at the moment.

**Comment by lucasresck** [comment]
Just in case, the extension deactivates but it keeps showing as active, right?

**Comment by LionelHolt** [comment]
Yes it shows as active, but it is not working, though I don't know whether that's because it's been silently deactivated or some other reason. Is there any other way besides the Gnome extensions list to detect its status?

**Comment by lucasresck** [comment]
It's possible to verify extension's status using the terminal:
```
gnome-extensions info alt-tab-scroll-workaround@lucasresck.github.io
```
It's also possible to manually check whether the extension is properly placed at `~/.local/share/gnome-shell/extensions`.

Not sure what else to do. Maybe debugging [`extension.js`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/main/extension.js)?

**Comment by LionelHolt** [comment]
Indeed this is a duplicate, so closing now.
