### ISSUE TITLE
Support for GNOME Flashback?

### ISSUE THREAD

**Issue by C-Duv** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#19]
Hello,

I am using *GNOME Flashback* (on Ubuntu 22.04 and Gnome v3.44) and I am experiencing the annoying alt-tab-scroll bug. Is there an (easy) to make your workaround compatible with *GNOME Flashback*?

**Comment by lucasresck** [comment]
Hi, thanks for reaching out!

I'm not sure if GNOME Extensions works with GNOME Flashback, I think it doesn't. Does it work for you?
