### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by L30Bola** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#20]
Can you please add support for Gnome 45? Gnome Shell 45 has a breaking change (another one, right?) for Extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by lucasresck** [comment]
Oh, my 😮 Is it reasonable to make a change that will literally break **all** extensions?

I'm not sure whether it will be possible to make the extension work with GNOME 45 and, when possible, how much work it will require. Let's keep this issue active.

Thank you for the update! Please, consider taking a look at [extension.js](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/blob/fede46dd2fb6fbd2368ca441754da87130c7e55e/extension.js) to check how the extension works. Maybe it's easy to solve it.

**Comment by Goldpaw** [comment]
I tried looking into it myself, with my fairly limited (read: none) knowledge of the gnome desktop. I followed the gnome guide to migrate extensions but quickly ran into an error that told me `WindowSwitcherPopup` now was a read-only method and couldn't be replaced. 

Is it even possible to do this in Gnome 45? o.O

**Comment by Goldpaw** [comment]
There are quite a lot of changes in Gnome 45, btw. They have made an official guide for migrating extensions, but it doesn't help with the issue of certain things now being read-only and no longer replacable. 

https://gjs.guide/extensions/upgrading/gnome-shell-45.html

**Comment by ld-web** [comment]
Hi everyone, I tried to fork and work on this, this is my first time contributing on Gnome extensions, so I had to read quite a lot of documentation to (kind of) understand how to use things, and didn't come to a working solution (yet).

However, I wanted to share the progress, just in case. Of course, if it's completely out of topic or doesn't help resolving the problem, don't mind it.

I tried to work around what @Goldpaw said, indeed, `WindowSwitcherPopup` is now a `const`, so I thought, maybe by trying to alter the prototype chain of the registered class, it could work. Or by replacing the implementation of the `_finish` method. But I'm not sure about how to do it properly.

I first tried to keep the classes defined in the extension, extending the `altTab` classes.
Then I switched to object initializers with the `__proto__` property set to the `altTab` classes.

Finally, I removed the `__proto__` property and just tried to directly use `AltTab.WindowSwitcherPopup.prototype._finish.bind(this)()`...But now I have a weird result, where Alt+Tab is very laggy, and doesn't work...which makes me think the problem may be the `pointer` module I decided to isolate in `src` ?

Everything is on [my fork, on the `gnome-45` branch](https://github.com/ld-web/gnome-shell-extension-alt-tab-scroll-workaround/tree/gnome-45).

Again, sorry if everything is completely wrong 😅

Cheers !

PS : btw, don't mind the `metadata.json` file, it was just for testing with another ID.

**Comment by lbltavares** [comment]
Hey guys, I'm also new here 👋

I think I've got it working for `WindowSwitcherPopup` (still working on `AppSwitcherPopup`)

I came across another Alt+Tab related extension that overrides the `_finish` method using `InjectionManager`: [Leleat/AltTab-Mod](https://github.com/Leleat/AltTab-Mod/blob/master/alttab-mod%40leleat-on-github/extension.js#L163)

So, I used his code as a base and simplified it until I reached this: [my fork](https://github.com/lbltavares/gnome-shell-extension-alt-tab-scroll-workaround/blob/main/extension.js)

Here's the main part:
```
        this._injectionManager = new InjectionManager();

        ...

        this._injectionManager.overrideMethod(
            AltTab.WindowSwitcherPopup.prototype,
            '_finish',
            (originalMethod) => {
                return function (timestamp) {
                    const [x, y] = global.get_pointer();
                    vdevice.notify_absolute_motion(global.get_current_time(), x, y);
                    Main.activateWindow(this._items[this._selectedIndex].window);
                    originalMethod.call(  
                        this,
                        timestamp
                    );
                };
            }
        );
```

For some reason it's not working for `AppSwitcherPopup`, but I'm currently looking into it

**Comment by ld-web** [comment]
Oh if I had found this `InjectionManager` before...thanks @lbltavares, gonna try this too to override the `_finish` method

**Comment by lbltavares** [comment]
Got it working for `AppSwitcherPopup`! I'll create the PR in a sec

**Comment by lbltavares** [comment]
Got it working on `AppSwitcherPopup`!
I'll create the PR in a second

> Oh if I had found this `InjectionManager` before...thanks @lbltavares, gonna try this too to override the `_finish` method

Don't even get me started! I spent the entire day on this poorly documented thing 😅 If it weren't for other similar extensions, I would have given up already

**Comment by ld-web** [comment]
Dang ! Got it working too with the `InjectionManager` I think ! I'll commit anyway, if you want we can review and exchange about it to see if versions match ? We can go with your PR of course. Thanks

**Comment by lbltavares** [comment]
Sure! Feel free to suggest anything, here it is: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/21

It's still very hacky, so I'll appreciate your review!

**Comment by ld-web** [comment]
Okay I didn't want to put too much review since we went different ways, so I opened mine : https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/22

Let's discuss and see what we can do (or not hahaha) ! Cheers

**Comment by lbltavares** [comment]
@ld-web Thanks for the suggestion! It indeed feels lighter having `movePointer` and `vdevice` outside the class. I merged your branch into mine :)
I also sometimes use `alt+esc` to switch windows directly and I noticed the bug was still there. So I added a fix for this in my PR. Additionally, I removed some redundant code in the injector callbacks (since we're calling `originalMethod`, there's no need to replicate it's logic inside the callback).

ps: I just realized we are 3 Lucas's working on this project 😄

**Comment by ld-web** [comment]
Nice ! I didn't notice for `Alt+Esc`, nice catch 💯 
Let's wait for @lucasresck feedback then

PS : Hahaha uniting Lucas' forces ! 💪🏻

**Comment by lucasresck** [comment]
Hey, guys! Thank you very much for this amazing discussion! I'm loving this haha

I'll review the pull request soon, thank you so much!

**Comment by Goldpaw** [comment]
> Hey, guys! Thank you very much for this amazing discussion! I'm loving this haha

The glory of open source. Windows and mac users definitely haven't got this kind of community! ;)

**Comment by lucasresck** [comment]
I am happy to announce the extension now supports GNOME 45! Changes are still in the `develop` branch but it will be included in `main` and released to GNOME Extensions soon!

I'll close this issue, but feel free to share more information if necessary.

Thank you for all work on this, specially @ld-web and @lbltavares for coming up with the solutions. Cheers!
