### ISSUE TITLE
Add support for hot corner

### ISSUE THREAD

**Issue by ld-web** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#24]
When reaching for hot corner (usually top left corner) to display all windows and then click on one to switch, it suddenly scrolls after switching, as it was with Alt + Tab or other switching methods.

@lbltavares [already suggested a solution](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/21#issuecomment-1784939899) (thanks, it was quick !), which has to be tested before opening a PR. It's for Gnome 45 (maybe we can add a "Gnome 45" label to the issue ?) :

```js
import * as Overview from "resource:///org/gnome/shell/ui/overview.js";
...
this._injectionManager.overrideMethod(
    Overview.Overview.prototype,
    '_showDone',
    (originalMethod) => {
        return function (...args) {
            movePointer();
            originalMethod.call(this, ...args);
        };
    }
);
```

**Comment by lucasresck** [comment]
Thank you, @ld-web, for this issue. It is indeed a great improvement to the extension. This can be solved before releasing `v5` (GNOME 45) and it can be added to [`v4`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/tree/v4) (GNOME <= 44) too. I intend to work on this soon, but feel free to also work on this. Thank you again!

**Comment by lucasresck** [comment]
My suggestion is including this change in a new pull request to [`develop`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/tree/develop) after merging https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/21. Then, after, creating another pull request to [`gjs-legacy-develop`](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/tree/gjs-legacy-develop) to add support to the previous version.

**Comment by lucasresck** [comment]
I've just created a PR: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/25. I'll use the extension for some days before merging it, but it has been working so far.

Thank you, @ld-web and @lbltavares, for noticing this and coming up with a solution.

**Comment by ld-web** [comment]
Thank you @lucasresck, I will pull it and test it locally as well, and then give you feedback !

**Comment by lucasresck** [comment]
I've already merged https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/pull/25. I'll still leave this issue open so that it can be approached for GNOME <= 44. Thanks everyone for all help!

**Comment by lucasresck** [comment]
In fact, it's better to open a new issue to work on this for GNOME <= 44.

**Comment by ld-web** [comment]
Sorry for the delay, everything looks good to me on v5, thanks !

**Comment by lucasresck** [comment]
Thank you for your feedback, @ld-web.

Just to update you, extension's `v5` went for review on GNOME Extensions but it was rejected: https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/28. I still need to work on this before releasing the update on GNOME Extensions.
