### ISSUE TITLE
Ubuntu MATE / Gnome 2 support?

### ISSUE THREAD

**Issue by nvaytet** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#31]
Hi!

Thanks a bunch for creating this.
Unfortunately for me, I'm using Ubuntu MATE, which is based on Gnome 2 and does not have Gnome extensions.
Is there any chance of getting something like this working for MATE/Gnome 2 desktops?

Thanks!

**Comment by lucasresck** [comment]
Hi, thanks for reaching out!

I think it's not possible to have it working for MATE, at least I'm not aware of any way to do that. Someone once [mentioned it](https://github.com/lucasresck/gnome-shell-extension-alt-tab-scroll-workaround/issues/3#issuecomment-1221413975) though.

Maybe the best approach in your case is sticking with the other quick fixes that people suggested on https://github.com/microsoft/vscode/issues/28795, e.g., installing `imwheel`?

Let me know if you find a fix for your case!
