### ISSUE TITLE
Release for GNOME 46?

### ISSUE THREAD

**Issue by FairySunny** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#35]
Thank you for the extension. Are there any plan to release for GNOME 46 on extensions.gnome.org? I changed the version in `metadata.json` and it works just fine.

**Comment by lucasresck** [comment]
Good to know it works with GNOME 46!

I have not had the opportunity to test GNOME 46 yet, but as soon as I have it I will upgrade the extension in the website.

In the meanwhile, if you want to, you can create a pull request with the upgrade.

Thanks for the feedback!

**Comment by bsa7** [comment]
Hello. First of all, I express my gratitude to the author of this extension.  
It looks like adapting this code for gnome 46 is quite simple. 

1. Open the metadata.json file in any editor and change version 45 to 46 and version 6 to 7
2. follow the instructions, starting with the `make install` and so on.

I have Ubuntu 24.04, Gnome 46. The scrolling bug has been fixed!

**Comment by lucasresck** [comment]
Hello, @bsa7, I will update the extension to GNOME 46 and release it in GNOME Extensions soon! But the process you did should work indeed.

**Comment by lucasresck** [comment]
Folks, thank you for waiting. The extension is updated and should be released in GNOME Extensions soon!
