### ISSUE TITLE
Extension cannot be enabled

### ISSUE THREAD

**Issue by egeecevit** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#39]
Hey there, I have the following setup:
![Screenshot from 2024-09-10 11-17-55](https://github.com/user-attachments/assets/6ed3dd4c-87f7-4aac-93fe-0d514b4a4939)

I have followed the instructions for installing from GitHub. However, I have the following output and `make enable` seems to be not working:

![Screenshot from 2024-09-10 11-19-10](https://github.com/user-attachments/assets/4fdb8d76-4483-4987-bb53-0a916566d280)

Any help would be appreciated.

**Comment by egeecevit** [comment]
I have installed gnome-shell-extensions with `sudo apt install gnome-shell-extensions` and manually enabled it with `gnome-extensions enable alt-tab-scroll-workaround@lucasresck.github.io`, then restarted Gnome which worked out!

**Comment by lucasresck** [comment]
Hi, @egeecevit, thank you for the issue. Happy to see that the problem has been solved.

Feel free to contact me again for any other issue, comment, or feedback.
