### ISSUE TITLE
How does one remove/uninstall the extension?

### ISSUE THREAD

**Issue by machineghost** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#4]
Since I'm on MATE this extension doesn't seem to help: how do I remove it?

**Comment by lucasresck** [comment]
You've installed the extension using `make`, is that correct? Please, try `make uninstall`.

**Comment by machineghost** [comment]
```
$ make uninstall
gnome-extensions uninstall alt-tab-scroll-workaround@lucasresck
make: *** [Makefile:13: uninstall] Error 2
```

**Comment by lucasresck** [comment]
What's the error when you directly type `gnome-extensions uninstall alt-tab-scroll-workaround@lucasresck`?

**Comment by machineghost** [comment]
There is none:

```
$ gnome-extensions uninstall alt-tab-scroll-workaround@lucasresck
$
```

Does that mean it's been removed?

**Comment by lucasresck** [comment]
I'm not sure. Please, check if the extension appears in the list returned by `gnome-extensions list`.

**Comment by machineghost** [comment]
```
$ gnome-extensions list
$
```

Looks like it's removed!  Thanks for all your help ... even though the MATE people did something screwy to make it not work for me!
