### ISSUE TITLE
Update extension on extensions.gnome.org for GNOME 43 compatibility

### ISSUE THREAD

**Issue by anoadragon453** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#7]
Hi there!

I'd like to use this extension with GNOME 43, however I've installed the extension from https://extensions.gnome.org/extension/5282/alttab-scroll-workaround/, which still only claims support for GNOME 42.

I'm not sure whether it's on the extension owner's side to update it or extensions.gnome.org to review an update. If it's the former, could you please update it? Thank you!

And thank you for continuing to maintain this useful extension :)

**Comment by lucasresck** [comment]
Hi, thanks for the reminder!

It was on my side, so I've just updated it. It should be working now.

**Comment by anoadragon453** [comment]
Cheers!
