### ISSUE TITLE
Scrolling issue back in v3

### ISSUE THREAD

**Issue by johvik** [lucasresck/gnome-shell-extension-alt-tab-scroll-workaround#9]
After upgrading from v2 to v3 the scrolling issue seems to be back occasionally.
Downgrading back to v2 seems to work though (though only had v2 again for a limited time, so I cannot swear it is the v3 just yet).

Also note that I've recently upgrade to gnome 43.

**Comment by lucasresck** [comment]
Hi, @johvik, thank you for your report.

Could you please provide more details about the issue coming back? Which is your OS and version? Can you describe a step-by-step to reproduce the error?

Thank you!

**Comment by johvik** [comment]
The issue I'm seeing is related to scrolling in vscode. It occasionally scrolls to the cursor for no good reason.
Not sure exactly how it is triggered, probably some magic combination of alt-tab, scrolling and switching windows or tabs :) I think it happened around 3 times in total during a day of work. Maybe if you have a reproduce how to trigger this issue in general I can try to play a bit around that?

I'm using fedora 37

**Comment by lucasresck** [comment]
Try this with the extension disabled or uninstalled:
- Open a long file in VS Code with window maximized (not full screen);
- At the same time, open a long web page in Google Chrome with window maximized;
- Switch between the two windows twice using `Alt+Tab`: VS Code -> Chrome -> VS Code;
- Scroll the VS Code down a sufficient amount of lines to visually identify the change;
- `Alt+Tab` for Chrome;
- Scroll Chrome down.

The VS Code scroll should be buffered and applied to Google Chrome as well, summing up with the last scroll you did in Chrome itself. With the extension enabled, however, the above steps shouldn't be able to do this.

**Comment by johvik** [comment]
Thanks, was able to use that to reproduce the issue without the extension. Unfortunately not with the extension v3 enabled. I will try to figure out how to reproduce it and will let you know if I manage. Maybe its just PEBCAK on my end :)

**Comment by lucasresck** [comment]
So in your tests the extension is working?

**Comment by johvik** [comment]
Yes, using your reproduce steps it works as expected. But I will continue to see if I can find a reproduce to the specific issue I see at my end

**Comment by lucasresck** [comment]
I see. Please, let me know if you can reproduce any issue.

**Comment by lucasresck** [comment]
Hi, @johvik, have you find any issue during your work?

**Comment by johvik** [comment]
I haven't found anything. One theory I have is that it might be system load related, possibly not related to the extension. But lets close this and I will reopen if I find that it could be some issue with the extension.
